CC=g++
CFLAGS=-I. -O3 -w
directory=build

all:
	mkdir -p $(directory)
# 	$(CC) $(CFLAGS) 01/puzzle_1.cpp -o $(directory)/1_puzzle_1
# 	$(CC) $(CFLAGS) 01/puzzle_2.cpp -o $(directory)/1_puzzle_2
# 	$(CC) $(CFLAGS) 02/puzzle_1.cpp -o $(directory)/2_puzzle_1
# 	$(CC) $(CFLAGS) 02/puzzle_2.cpp -o $(directory)/2_puzzle_2
# 	$(CC) $(CFLAGS) 03/puzzle_1.cpp -o $(directory)/3_puzzle_1
# 	$(CC) $(CFLAGS) 03/puzzle_2.cpp -o $(directory)/3_puzzle_2
# 	$(CC) $(CFLAGS) 04/puzzle_1.cpp -o $(directory)/4_puzzle_1
# 	$(CC) $(CFLAGS) 04/puzzle_2.cpp -o $(directory)/4_puzzle_2
# 	$(CC) $(CFLAGS) 05/puzzle_1.cpp -o $(directory)/5_puzzle_1
# 	$(CC) $(CFLAGS) 05/puzzle_2.cpp -o $(directory)/5_puzzle_2
	$(CC) $(CFLAGS) 06/puzzle_1.cpp -o $(directory)/6_puzzle_1
	$(CC) $(CFLAGS) 06/puzzle_2.cpp -o $(directory)/6_puzzle_2
