CC=g++
CFLAGS=-I. -O3 -w
directory=build

all:
	mkdir -p $(directory)
	$(CC) $(CFLAGS) 01/puzzle_1.cpp -o $(directory)/1_puzzle_1
	$(CC) $(CFLAGS) 01/puzzle_2.cpp -o $(directory)/1_puzzle_2
	$(CC) $(CFLAGS) 02/puzzle_1.cpp -o $(directory)/2_puzzle_1
	$(CC) $(CFLAGS) 02/puzzle_2.cpp -o $(directory)/2_puzzle_2
