CC=g++ -std=c++17
CFLAGS=-I. -O3 -w
directory=build

all:
	mkdir -p $(directory)
	$(CC) $(CFLAGS) 15/puzzle_1.cpp -o $(directory)/15_puzzle_1
	$(CC) $(CFLAGS) 15/puzzle_2.cpp -o $(directory)/15_puzzle_2
	$(CC) $(CFLAGS) 15/puzzle_2_slow.cpp -o $(directory)/15_puzzle_2_slow
#	$(CC) $(CFLAGS) 14/puzzle_1.cpp -o $(directory)/14_puzzle_1
#	$(CC) $(CFLAGS) 14/puzzle_2.cpp -o $(directory)/14_puzzle_2
#	$(CC) $(CFLAGS) 13/puzzle_1.cpp -o $(directory)/13_puzzle_1
#	$(CC) $(CFLAGS) 12/puzzle_1.cpp -o $(directory)/12_puzzle_1
#	$(CC) $(CFLAGS) 12/puzzle_2.cpp -o $(directory)/12_puzzle_2
#	$(CC) $(CFLAGS) 10/puzzle_1.cpp -o $(directory)/10_puzzle_1
#	$(CC) $(CFLAGS) 10/puzzle_2.cpp -o $(directory)/10_puzzle_2
#	$(CC) $(CFLAGS) 09/puzzle_1.cpp -o $(directory)/9_puzzle_1
#	$(CC) $(CFLAGS) 09/puzzle_2.cpp -o $(directory)/9_puzzle_2
#	$(CC) $(CFLAGS) 08/puzzle_1.cpp -o $(directory)/8_puzzle_1
#	$(CC) $(CFLAGS) 08/puzzle_2.cpp -o $(directory)/8_puzzle_2
#	$(CC) $(CFLAGS) 07/puzzle_1.cpp -o $(directory)/7_puzzle_1
#	$(CC) $(CFLAGS) 07/puzzle_2.cpp -o $(directory)/7_puzzle_2
#	$(CC) $(CFLAGS) 06/puzzle_1.cpp -o $(directory)/6_puzzle_1
#	$(CC) $(CFLAGS) 06/puzzle_2.cpp -o $(directory)/6_puzzle_2
#	$(CC) $(CFLAGS) 05/puzzle_1.cpp -o $(directory)/5_puzzle_1
#	$(CC) $(CFLAGS) 05/puzzle_2.cpp -o $(directory)/5_puzzle_2
#	$(CC) $(CFLAGS) 04/puzzle_1.cpp -o $(directory)/4_puzzle_1
#	$(CC) $(CFLAGS) 04/puzzle_2.cpp -o $(directory)/4_puzzle_2
#	$(CC) $(CFLAGS) 03/puzzle_1.cpp -o $(directory)/3_puzzle_1
#	$(CC) $(CFLAGS) 03/puzzle_2.cpp -o $(directory)/3_puzzle_2
#	$(CC) $(CFLAGS) 02/puzzle_1.cpp -o $(directory)/2_puzzle_1
#	$(CC) $(CFLAGS) 02/puzzle_2.cpp -o $(directory)/2_puzzle_2
#	$(CC) $(CFLAGS) 01/puzzle_1.cpp -o $(directory)/1_puzzle_1
#	$(CC) $(CFLAGS) 01/puzzle_2.cpp -o $(directory)/1_puzzle_2
